spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/carteira
        username: postgres
        password: postgres
    jpa:
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    jackson:
        serialization.INDENT_OUTPUT: true             

server:
    port: 9090
    context-path: /carteira
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
swagger:
    title: Financas 
    description: Financas
    version: v1
    termsOfServiceUrl: http://www.carteira.com.br/terms/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html        

springfox:
    documentation:
        swagger.v2.path: /docs        